image: python:3.9

services:
  - name: mysql:latest

variables:
  MYSQL_ROOT_PASSWORD: alatreon
  MYSQL_DATABASE: repel

before_script:
  - pip install pytest pymysql

pytest:
  script:
    - cd $CI_PROJECT_DIR
    - pytest
