insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (1, 'Embrace of the Vampire', 6028, 1990, 'Horror', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (2, 'Acla, The Descent into Floristella (La discesa di Aclà a Floristella)', 6797, 2005, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (3, 'Lost Weekend, The', 6442, 1993, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (4, 'Fixed Bayonets!', 5836, 2005, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (5, 'Antibodies (Antikörper)', 6873, 2001, 'Crime', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (6, 'Castle in the Desert (Charlie Chan in Castle in the Desert)', 6372, 1996, 'Comedy', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (7, 'Dragon Lord (a.k.a. Dragon Strike) (Long Xiao Ye)', 6861, 2006, 'Action', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (8, 'Cold Comfort Farm', 5618, 2005, 'Comedy', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (9, 'The Burglar', 6556, 1987, 'Crime', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (10, 'Dead & Buried', 5579, 2004, 'Horror', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (11, 'Thunderheart', 5896, 1988, 'Crime', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (12, 'Mother Carey''s Chickens', 6596, 2004, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (13, 'Frontière(s)', 5688, 1993, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (14, 'Flight of Fury', 5959, 1985, 'Action', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (15, 'Stuck', 6708, 2014, 'Horror', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (16, 'Intimate Strangers (Confidences trop intimes)', 6992, 2018, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (17, 'Films to Keep You Awake: The Baby''s Room (Películas para no dormir: La habitación del niño)', 6116, 1990, 'Horror', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (18, 'Headhunter''s Sister, The', 5943, 1998, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (19, 'Good Man in Africa, A', 5762, 2012, 'Action', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (20, 'Host, The', 7118, 1999, 'Action', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (21, 'Monster, The', 6528, 1988, 'Comedy', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (22, 'Ella Lola, a la Trilby', 5703, 2000, '(no genres listed)', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (23, 'Please Vote for Me', 7168, 2004, 'Documentary', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (24, 'Blood, Guts, Bullets and Octane', 5690, 2001, 'Action', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (25, 'The Cruel Sea', 6176, 2000, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (26, 'Munger Road', 6008, 1991, 'Horror', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (27, 'Girl Crazy', 5666, 2008, 'Comedy', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (28, 'Sometimes They Come Back... for More', 6001, 2010, 'Horror', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (29, 'The World Forgotten', 6038, 1999, 'Adventure', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (30, 'Hunting Party, The', 6915, 2004, 'Action', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (31, 'Ink', 5651, 1999, 'Action', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (32, '2010: The Year We Make Contact', 6225, 1992, 'Sci-Fi', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (33, 'Naked Edge, The', 5652, 2007, 'Thriller', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (34, 'Baby On Board', 6182, 1997, 'Comedy', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (35, 'After Life (Wandafuru raifu)', 6955, 1989, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (36, 'Backcountry', 5602, 2002, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (37, 'Mr. Magoo', 6755, 1989, 'Comedy', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (38, 'Street Without End (Kagirinaki hodo)', 6646, 1997, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (39, 'Blaze', 5796, 2012, 'Comedy', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (40, 'Sympathy for Delicious', 6312, 1988, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (41, 'The Message', 6988, 2012, 'Crime', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (42, 'Food Stamped', 5641, 2002, 'Documentary', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (43, 'Cat Run 2', 6420, 2017, 'Action', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (44, 'Girl in the Cadillac', 7025, 2020, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (45, 'The Secret of Convict Lake', 6434, 2005, 'Western', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (46, 'Lost World, The', 7150, 1994, 'Adventure', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (47, 'Why Me?', 6998, 1998, 'Drama', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (48, 'Triad Election (a.k.a. Election 2) (Hak se wui yi wo wai kwai)', 6063, 2002, 'Crime', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (49, 'Check and Double Check', 6805, 2004, 'Comedy', null);
insert into movies (movies_id, name, duration, release_year, genre, synopsis) values (50, 'Two People', 6967, 1989, 'Drama', null);
