insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (1, 'Embrace of the Vampire', 6028, 1990, 'Horror', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (2, 'Acla, The Descent into Floristella (La discesa di Aclà a Floristella)', 6797, 2005, 'Drama', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (3, 'Lost Weekend, The', 6442, 1993, 'Drama', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (4, 'Fixed Bayonets!', 5836, 2005, 'Drama', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (5, 'Antibodies (Antikörper)', 6873, 2001, 'Crime', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (6, 'Castle in the Desert (Charlie Chan in Castle in the Desert)', 6372, 1996, 'Comedy', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (7, 'Dragon Lord (a.k.a. Dragon Strike) (Long Xiao Ye)', 6861, 2006, 'Action', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (8, 'Cold Comfort Farm', 5618, 2005, 'Comedy', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (9, 'The Burglar', 6556, 1987, 'Crime', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (10, 'Dead & Buried', 5579, 2004, 'Horror', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (11, 'Thunderheart', 5896, 1988, 'Crime', null, 3, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (12, 'Mother Carey''s Chickens', 6596, 2004, 'Drama', null, 5, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (13, 'Frontière(s)', 5688, 1993, 'Drama', null, 5, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (14, 'Flight of Fury', 5959, 1985, 'Action', null, 5, 12);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (15, 'Stuck', 6708, 2014, 'Horror', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (16, 'Intimate Strangers (Confidences trop intimes)', 6992, 2018, 'Drama', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (17, 'Films to Keep You Awake: The Baby''s Room (Películas para no dormir: La habitación del niño)', 6116, 1990, 'Horror', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (18, 'Headhunter''s Sister, The', 5943, 1998, 'Drama', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (19, 'Good Man in Africa, A', 5762, 2012, 'Action', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (20, 'Host, The', 7118, 1999, 'Action', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (21, 'Monster, The', 6528, 1988, 'Comedy', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (22, 'Ella Lola, a la Trilby', 5703, 2000, '(no genres listed)', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (23, 'Please Vote for Me', 7168, 2004, 'Documentary', null, 5, 7);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (24, 'Blood, Guts, Bullets and Octane', 5690, 2001, 'Action', null, 5, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (25, 'The Cruel Sea', 6176, 2000, 'Drama', null, 5, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (26, 'Munger Road', 6008, 1991, 'Horror', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (27, 'Girl Crazy', 5666, 2008, 'Comedy', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (28, 'Sometimes They Come Back... for More', 6001, 2010, 'Horror', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (29, 'The World Forgotten', 6038, 1999, 'Adventure', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (30, 'Hunting Party, The', 6915, 2004, 'Action', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (31, 'Ink', 5651, 1999, 'Action', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (32, '2010: The Year We Make Contact', 6225, 1992, 'Sci-Fi', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (33, 'Naked Edge, The', 5652, 2007, 'Thriller', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (34, 'Baby On Board', 6182, 1997, 'Comedy', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (35, 'After Life (Wandafuru raifu)', 6955, 1989, 'Drama', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (36, 'Backcountry', 5602, 2002, 'Drama', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (37, 'Creep', 6543, 2001, 'Horror', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (38, 'Good Bye Lenin!', 6214, 1994, 'Comedy', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (39, 'Buried Alive II', 6963, 2008, 'Horror', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (40, 'Outrage', 6601, 1986, 'Drama', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (41, 'Philadelphia Experiment II', 5744, 2005, 'Sci-Fi', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (42, 'Curse of the Pink Panther', 6671, 2012, 'Comedy', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (43, 'Faster, Pussycat! Kill! Kill!', 6081, 2010, 'Action', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (44, 'Music for the Movies: Bernard Herrmann', 6064, 2002, 'Documentary', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (45, 'Fists in the Pocket (I Pugni in Tasca)', 6155, 2007, 'Drama', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (46, 'Mindwarp', 6166, 1986, 'Horror', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (47, 'Herb & Dorothy', 6248, 2001, 'Documentary', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (48, '2012', 6651, 2001, 'Action', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (49, 'Diary of the Dead (a.k.a. George A. Romero''s Diary of the Dead)', 7096, 2000, 'Horror', null, 9, 8);
insert into series (series_id, name, duration, release_year, genre, synopsis, season, episode) values (50, 'Poseidon Adventure, The', 6316, 2000, 'Action', null, 9, 8);
